version: '3'

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

services:
  server:
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - .:/opt/project:delegated
      - ../conf:/opt/conf
    networks:
      - dev
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:8000


