# Generated by Django 3.1.7 on 2021-09-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('from_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='core.account')),
                ('to_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='core.account')),
            ],
        ),
    ]
