# Generated by Django 3.1.7 on 2021-09-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='money',
            new_name='amount',
        ),
    ]
